build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "42ebfa78d8908942f2b8049ed7c8a819092d8bea79f2edca1bbc686aa831776dca5ed77bd7637cc086978df002c9a7ae"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371